services:
  web:
    build: .
    restart: always
    container_name: playit-shop-backend
    env_file:
      - .env
    ports:
     - "8002:8002"
    networks:
      - skynet

networks:
  skynet:
    external: true